#!/bin/bash

./modes.pl "revisedGrailPsalter/Psalm\ 1" three a b > Psalm1.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 2" two a_prime b > Psalm2.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 3" one a b > Psalm3.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 4" six a b > Psalm4.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 5" one a_prime b_prime > Psalm5.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 6" four a b > Psalm6.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 7" three a b > Psalm7.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 8" seven a b > Psalm8.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 9" seven b_prime a > Psalm9.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 10" seven a b_prime > Psalm10.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11" eight a_dprime b > Psalm11.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 12" peregrinus a b > Psalm12.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 13" seven a b_prime > Psalm13.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 14" one a_prime b_prime > Psalm14.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 15" eight a_dprime b > Psalm15.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 16" four b_prime a_prime > Psalm16.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 17" five a_prime b > Psalm17.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 18" two a_prime b > Psalm18.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 19" eight a_dprime b > Psalm19.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 20" three b a > Psalm20.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 21" four b_prime a_prime > Psalm21.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 22" one a_prime b_prime > Psalm22.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 23" four a b > Psalm23.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 24" peregrinus a b > Psalm24.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 25" six b a_prime > Psalm25.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 26" five a_prime b > Psalm26.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 27" eight a_dprime b > Psalm27.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;



echo "\documentclass[10pt,letterpaper,twoside]{report}" > newPsalter.tex;
echo "\usepackage{verse}" >> newPsalter.tex;
echo "\usepackage{psalter}" >> newPsalter.tex;
echo "\begin{document}" >> newPsalter.tex;
for i in `seq 1 27`; do echo "\input{Psalm$i}" >> newPsalter.tex; done
echo "\end{document}" >> newPsalter.tex;
