#!/bin/bash

./modes.pl "revisedGrailPsalter/Psalm\ 1" three a b > Psalm1.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 2" two a_prime b > Psalm2.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 3" one a b > Psalm3.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 4" six a b > Psalm4.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 5" one a_prime b_prime > Psalm5.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 6" four a b > Psalm6.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 7" three a b > Psalm7.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 8" seven a b > Psalm8.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 9" seven b_prime a > Psalm9.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 10" seven a b_prime > Psalm10.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11" eight a_dprime b > Psalm11.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 12" peregrinus a b > Psalm12.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 13" seven a b_prime > Psalm13.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 14" one a_prime b_prime > Psalm14.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 15" eight a_dprime b > Psalm15.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 16" four b_prime a_prime > Psalm16.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 17" five a_prime b > Psalm17.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 18" two a_prime b > Psalm18.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 19" eight a_dprime b > Psalm19.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 20" three b a > Psalm20.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 21" four b_prime a_prime > Psalm21.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 22" one a_prime b_prime > Psalm22.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 23" four a b > Psalm23.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 24" peregrinus a b > Psalm24.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 25" six b a_prime > Psalm25.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 26" five a_prime b > Psalm26.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 27" eight a_dprime b > Psalm27.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 28" two a_prime b > Psalm28.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 29" eight a_dprime b > Psalm29.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 30" six a b > Psalm30.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 31" six a b > Psalm31.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 32" one b_dprime a_prime > Psalm32.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 33" five a_prime b > Psalm33.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 34" five a_prime b > Psalm34.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 35" one a b > Psalm35.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 36" six b a > Psalm36.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 37" two a_prime b > Psalm37.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 38" two a_prime b > Psalm38.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 39" seven b a > Psalm39.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 40" four a_prime b_prime > Psalm40.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 41" six b a_prime > Psalm41.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 42" one a b > Psalm42.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 43" three a b > Psalm43.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 44" peregrinus a b > Psalm44.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 45" eight a_prime b > Psalm45.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 46" five a_prime b > Psalm46.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 47" two a_prime b > Psalm47.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 48" five a_prime b > Psalm48.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 49" four a_prime b_prime > Psalm49.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 50" one a_prime b_prime > Psalm50.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 51" eight a_dprime b > Psalm51.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 52" one a_prime b_prime > Psalm52.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 53" two b a > Psalm53.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 54" six a b > Psalm54.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;
# ./modes.pl "revisedGrailPsalter/Psalm\ 1" one a b > Psalm1.tex;



echo "\documentclass[10pt,letterpaper,twoside]{report}" > newPsalter.tex;
echo "\usepackage{verse}" >> newPsalter.tex;
echo "\usepackage{psalter}" >> newPsalter.tex;
echo "\begin{document}" >> newPsalter.tex;
for i in `seq 1 49`; do echo "\input{Psalm$i}" >> newPsalter.tex; done
echo "\end{document}" >> newPsalter.tex;
#echo "\documentclass[10pt,letterpaper,twoside]{report}" > newPsalter1-49.tex;
#echo "\usepackage{verse}" >> newPsalter1-49.tex;
#echo "\usepackage{psalter}" >> newPsalter1-49.tex;
#echo "\begin{document}" >> newPsalter1-49.tex;
#for i in `seq 1 49`; do echo "\input{Psalm$i}" >> newPsalter1-49.tex; done
#echo "\end{document}" >> newPsalter1-49.tex;
#echo "\documentclass[10pt,letterpaper,twoside]{report}" > newPsalter50-99.tex;
#echo "\usepackage{verse}" >> newPsalter50-99.tex;
#echo "\usepackage{psalter}" >> newPsalter50-99.tex;
#echo "\begin{document}" >> newPsalter50-99.tex;
#for i in `seq 50 54`; do echo "\input{Psalm$i}" >> newPsalter50-99.tex; done
#echo "\end{document}" >> newPsalter50-99.tex;
