#!/bin/bash

./modes.pl "revisedGrailPsalter/Psalm\ 1" three a b | sed -f sedaccents > Psalm001.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 2" two a_prime b | sed -f sedaccents > Psalm002.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 3" one a b | sed -f sedaccents > Psalm003.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 4" six a b | sed -f sedaccents > Psalm004.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 5" one a_prime b_prime | sed -f sedaccents > Psalm005.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 6" four a b | sed -f sedaccents > Psalm006.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 7" three a b | sed -f sedaccents > Psalm007.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 8" seven a b | sed -f sedaccents | sed -f sedaccents > Psalm008.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 9" seven b_prime a | sed -f sedaccents > Psalm009A.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 10" seven a b_prime | sed -f sedaccents > Psalm009B.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11" eight a_dprime b | sed -f sedaccents > Psalm010.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 12" peregrinus a b | sed -f sedaccents > Psalm011.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 13" seven a b_prime | sed -f sedaccents > Psalm012.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 14" two b a | sed -f sedaccents > Psalm013.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 15" eight a_dprime b | sed -f sedaccents > Psalm014.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 16" four b_prime a_prime | sed -f sedaccents > Psalm015.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 17" five a_prime b | sed -f sedaccents > Psalm016.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 18" two a_prime b | sed -f sedaccents > Psalm017.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 19" eight a_dprime b | sed -f sedaccents > Psalm018.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 20" three b a | sed -f sedaccents > Psalm019.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 21" four b_prime a_prime | sed -f sedaccents > Psalm020.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 22" one a_prime b_prime | sed -f sedaccents > Psalm021.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 23" four a b | sed -f sedaccents > Psalm022.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 24" peregrinus a b | sed -f sedaccents > Psalm023.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 25" six b a_prime | sed -f sedaccents > Psalm024.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 26" five a_prime b | sed -f sedaccents > Psalm025.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 27" eight a_dprime b | sed -f sedaccents > Psalm026.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 28" two a_prime b | sed -f sedaccents > Psalm027.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 29" eight a_dprime b | sed -f sedaccents > Psalm028.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 30" six a b | sed -f sedaccents > Psalm029.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 31" six a b | sed -f sedaccents > Psalm030.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 32" one b_dprime a_prime | sed -f sedaccents > Psalm031.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 33" five a_prime b | sed -f sedaccents > Psalm032.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 34" five a_prime b | sed -f sedaccents > Psalm033.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 35" one a b | sed -f sedaccents > Psalm034.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 36" six b a | sed -f sedaccents > Psalm035.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 37" two a_prime b | sed -f sedaccents > Psalm036.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 38" two a_prime b | sed -f sedaccents > Psalm037.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 39" seven b a | sed -f sedaccents > Psalm038.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 40" four a_prime b_prime | sed -f sedaccents > Psalm039.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 41" six b a_prime | sed -f sedaccents > Psalm040.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 42" one a b | sed -f sedaccents > Psalm041.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 43" three a b | sed -f sedaccents > Psalm042.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 44" peregrinus a b | sed -f sedaccents > Psalm043.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 45" eight a_prime b | sed -f sedaccents > Psalm044.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 46" four a_prime b_prime | sed -f sedaccents > Psalm045.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 47" five a_prime b | sed -f sedaccents > Psalm046.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 48" two a_prime b | sed -f sedaccents > Psalm047.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 49" five a b | sed -f sedaccents > Psalm048.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 50" four a_prime b_prime | sed -f sedaccents > Psalm049.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 51" one a_prime b_prime | sed -f sedaccents > Psalm050.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 52" eight a_dprime b | sed -f sedaccents > Psalm051.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 53" one a_prime b_prime | sed -f sedaccents > Psalm052.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 54" two b a | sed -f sedaccents > Psalm053.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 55" three b a | sed -f sedaccents > Psalm054.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 56" three b a | sed -f sedaccents > Psalm055.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 57" six a b | sed -f sedaccents > Psalm056.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 58" four b a | sed -f sedaccents > Psalm057.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 59" three a b | sed -f sedaccents > Psalm058.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 60" one b a | sed -f sedaccents > Psalm059.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 61" two a_prime b | sed -f sedaccents > Psalm060.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 62" eight a b | sed -f sedaccents > Psalm061.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 63" one a b | sed -f sedaccents > Psalm062.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 64" one b a | sed -f sedaccents > Psalm063.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 65" three b a | sed -f sedaccents > Psalm064.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 66" two a_prime b | sed -f sedaccents > Psalm065.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 67" five a_prime b | sed -f sedaccents > Psalm066.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 68" two a_prime b | sed -f sedaccents > Psalm067.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 69" seven b_prime a | sed -f sedaccents > Psalm068.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 70" one a b | sed -f sedaccents > Psalm069.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 71" six b a_prime | sed -f sedaccents > Psalm070.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 72" seven a b | sed -f sedaccents > Psalm071.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 73" one a_prime b_prime | sed -f sedaccents > Psalm072.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 74" eight a b | sed -f sedaccents > Psalm073.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 75" four a b | sed -f sedaccents > Psalm074.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 76" five a_prime b | sed -f sedaccents > Psalm075.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 77" three a b | sed -f sedaccents > Psalm076.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 7800" one a b | sed -f sedaccents > Psalm077A.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 7801" six b a_prime | sed -f sedaccents > Psalm077B.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 79" two a b | sed -f sedaccents > Psalm078.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 80" three a b | sed -f sedaccents > Psalm079.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 81" seven a b_prime | sed -f sedaccents > Psalm080.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 82" eight a_dprime b | sed -f sedaccents > Psalm081.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 83" three b a | sed -f sedaccents > Psalm082.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 84" peregrinus a b | sed -f sedaccents > Psalm083.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 85" five a_prime b | sed -f sedaccents > Psalm084.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 86" four a_prime b_prime | sed -f sedaccents > Psalm085.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 87" two a b | sed -f sedaccents > Psalm086.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 8800" six a b | sed -f sedaccents > Psalm087.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 8801" one a_prime b_prime | sed -f sedaccents > Psalm088A.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 89" eight a_dprime b | sed -f sedaccents > Psalm088B.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 90" eight a_dprime b | sed -f sedaccents > Psalm089.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 91" four b_prime a_prime | sed -f sedaccents > Psalm090.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 92" one b_prime a_prime | sed -f sedaccents > Psalm091.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 93" five a_prime b | sed -f sedaccents > Psalm092.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 94" three a b | sed -f sedaccents > Psalm093.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 95" seven a b | sed -f sedaccents > Psalm094.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 96" two b a | sed -f sedaccents > Psalm095.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 97" five a_prime b | sed -f sedaccents > Psalm096.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 98" five b a_prime | sed -f sedaccents > Psalm097.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 99" six b a | sed -f sedaccents > Psalm098.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 100" five a_prime b | sed -f sedaccents > Psalm099.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 101" four b a | sed -f sedaccents > Psalm0100.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 102" two a b | sed -f sedaccents > Psalm0101.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 103" seven b a | sed -f sedaccents > Psalm0102.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 104" one a_prime b_prime | sed -f sedaccents > Psalm0103.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 105" six b a_prime | sed -f sedaccents > Psalm0104.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 106" one a_prime b | sed -f sedaccents > Psalm0105.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 107" five b a_prime | sed -f sedaccents > Psalm0106.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 108" two a_prime b | sed -f sedaccents > Psalm0107.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 109" three a b | sed -f sedaccents > Psalm0108.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 110" five b a_prime | sed -f sedaccents > Psalm0109.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 111" seven a b_prime | sed -f sedaccents > Psalm0110.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 112" eight a b | sed -f sedaccents > Psalm0111.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 113" peregrinus a b | sed -f sedaccents > Psalm0112.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 114" two b a | sed -f sedaccents > Psalm0113.tex;
#our 113 is the grail's 114 and 115 put together
./modes.pl "revisedGrailPsalter/Psalm\ 116A" four b a_prime | sed -f sedaccents > Psalm0114.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 116B" eight a_dprime b | sed -f sedaccents > Psalm0115.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 117" seven a b | sed -f sedaccents > Psalm0116.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 118" five a_prime b | sed -f sedaccents > Psalm0117.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11900" one b a | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11901" three a b | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11902" two a b | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11903" four a_prime b_prime | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11904" five a_prime b | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11905" six b a_prime | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11906" seven b a | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11907" eight a_prime b | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11908" peregrinus b a | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11909" one a b | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 11910" four a b | sed -f sedaccents > Psalm0118.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 120" four b_prime a_prime | sed -f sedaccents > Psalm0119.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 121" six b a | sed -f sedaccents > Psalm0120.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 122" five a_prime b | sed -f sedaccents > Psalm0121.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 123" three a b | sed -f sedaccents > Psalm0122.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 124" one b_prime a_prime | sed -f sedaccents > Psalm0123.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 125" peregrinus b a | sed -f sedaccents > Psalm0124.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 126" two b a_prime | sed -f sedaccents > Psalm0125.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 127" seven a b | sed -f sedaccents > Psalm0126.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 128" eight b a_dprime | sed -f sedaccents > Psalm0127.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 129" six a_prime b | sed -f sedaccents > Psalm0128.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 130" four a_prime b | sed -f sedaccents > Psalm0129.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 131" eight b a_dprime | sed -f sedaccents > Psalm0130.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 132" one b a | sed -f sedaccents > Psalm0131.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 133" three a b | sed -f sedaccents > Psalm0132.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 134" six a b | sed -f sedaccents > Psalm0133.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 135" seven a b | sed -f sedaccents > Psalm0134.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 136" peregrinus a b | sed -f sedaccents > Psalm0135.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 137" three b a | sed -f sedaccents > Psalm0136.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 138" two a_prime b | sed -f sedaccents > Psalm0137.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 139" eight a_prime b | sed -f sedaccents > Psalm0138.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 140" four a b | sed -f sedaccents > Psalm0139.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 141" six a b | sed -f sedaccents > Psalm0140.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 142" three b a | sed -f sedaccents > Psalm0141.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 143" four a_prime b_prime | sed -f sedaccents > Psalm0142.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 144" five a_prime b | sed -f sedaccents > Psalm0143.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 145" eight a_dprime b | sed -f sedaccents > Psalm0144.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 146" seven a b | sed -f sedaccents > Psalm0145.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 147A" six a_prime b | sed -f sedaccents > Psalm0146.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 147B" four b_prime a_prime | sed -f sedaccents > Psalm0147.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 148" five a_prime b | sed -f sedaccents > Psalm0148.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 149" eight a_dprime b | sed -f sedaccents > Psalm0149.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 150" peregrinus a b | sed -f sedaccents > Psalm0150.tex;
./modes.pl "revisedGrailPsalter/Psalm\ 150" seven a b | sed -f sedaccents > Psalm0150.tex;
#two mode options for psalm 150 in french psalter

echo "\documentclass[12pt,twoside,a5paper]{memoir}" > newPsalter.tex;
echo "\usepackage{verse}" >> newPsalter.tex;
echo "\usepackage{../psaltertitle}" >> newPsalter.tex;
echo "\usepackage{xunicode}" >> newPsalter.tex;
echo "\usepackage{fontspec}" >> newPsalter.tex;
echo "\usepackage{xltxtra}" >> newPsalter.tex;
echo "\setmainfont[Mapping=tex-text,Numbers=OldStyle]{Adobe Jenson Pro}" >> newPsalter.tex;
echo "\usepackage{../psalter}"  >> newPsalter.tex;
echo "\semiisopage[8]" >> newPsalter.tex;
#echo "\setstocksize{210mm}{148mm}" >> newPsalter.tex;
#echo "\settrimmedsize{195mm}{125mm}{*}" >> newPsalter.tex;
#echo "\setlength{\trimtop}{0pt}" >> newPsalter.tex;
#echo "\setlength{\trimedge}{\stockwidth}" >> newPsalter.tex;
#echo "\addtolength{\trimedge}{-\paperwidth}" >> newPsalter.tex;
#echo "\settrims{5mm}{0mm}" >> newPsalter.tex;
#echo "\settypeblocksize{180mm}{120mm}{*}" >> newPsalter.tex;
#echo "\setlrmarginsandblock{.4cm}{*}{*}" >> newPsalter.tex;
#echo "\setulmarginsandblock{.9cm}{*}{*}" >> newPsalter.tex;
#echo "\setlrmargins{*}{*}{1.8}" >> newPsalter.tex;
#echo "\setheadfoot{\onelineskip}{\onelineskip}" >> newPsalter.tex;
#echo "\setheaderspaces{*}{\onelineskip}{*}" >> newPsalter.tex;
echo "\checkandfixthelayout" >> newPsalter.tex;
echo "\nouppercaseheads" >> newPsalter.tex;
echo "\begin{document}" >> newPsalter.tex;
echo "\pagestyle{empty}" >> newPsalter.tex;
echo "\titleWH" >> newPsalter.tex;
echo "\clearpage" >> newPsalter.tex;
echo "\setcounter{page}{1}" >> newPsalter.tex;
echo "\makepagestyle{psalter}" >> newPsalter.tex;
echo "\makeoddhead{psalter}{\textcolor{red}{\leftmark}}{}{}" >> newPsalter.tex;
echo "\makeevenhead{psalter}{}{}{\textcolor{red}{\rightmark}}" >> newPsalter.tex;
echo "\makeoddfoot{psalter}{\textcolor{red}{\thepage}}{}{}" >> newPsalter.tex;
echo "\makeevenfoot{psalter}{}{}{\textcolor{red}{\thepage}}" >> newPsalter.tex;
#echo "\makepsmarks{psalter}{" >> newPsalter.tex;
#echo "\createmark{poemtitle}{both}{nonumber}{}{}}" >> newPsalter.tex;
echo "\PlainPoemTitle" >> newPsalter.tex;
echo "\pagestyle{psalter}" >> newPsalter.tex;
echo "\renewcommand*{\poemtitlemark}[1]{\markboth{#1}{#1}}" >> newPsalter.tex;
echo "\renewcommand*{\PoemTitlefont}{\centering\scshape\large}" >> newPsalter.tex;
for i in `ls Psalm*|grep Psalm*[0-9]`; do export psalm=$(echo $i|sed 's/Psalm0*\([1-9][0-9]*[AB]*\)\.tex/\1/g;'); echo "\needspace{3\baselineskip}" >> newPsalter.tex; echo "\PoemTitle[ps. $psalm]{\textline[t]{\hfill}{$(head ../en-US/p$psalm.ly |awk -F"\"" '{if ($1 ~/markup/){printf $2}}')}{$(head ../en-US/p$psalm.ly |awk -F"\"" '{if ($1 ~ /markup/){printf $4}}')}}" >> newPsalter.tex; echo "\input{`basename $i .tex`}" >> newPsalter.tex; done

echo "\end{document}" >> newPsalter.tex;
#echo "\documentclass[10pt,letterpaper,twoside]{report}" > newPsalter1-49.tex;
#echo "\usepackage{verse}" >> newPsalter1-49.tex;
#echo "\usepackage{psalter}" >> newPsalter1-49.tex;
#echo "\begin{document}" >> newPsalter1-49.tex;
#for i in `seq 1 49`; do echo "\input{Psalm$i}" >> newPsalter1-49.tex; done
#echo "\end{document}" >> newPsalter1-49.tex;
#echo "\documentclass[10pt,letterpaper,twoside]{report}" > newPsalter50-99.tex;
#echo "\usepackage{verse}" >> newPsalter50-99.tex;
#echo "\usepackage{psalter}" >> newPsalter50-99.tex;
#echo "\begin{document}" >> newPsalter50-99.tex;
#for i in `seq 50 54`; do echo "\input{Psalm$i}" >> newPsalter50-99.tex; done
#echo "\end{document}" >> newPsalter50-99.tex;
sed -i 's/p9.ly/p9A.ly/' Psalm009A.tex;
sed -i 's/p9.ly/p9B.ly/' Psalm009B.tex;
sed -i 's/p77.ly/p77A.ly/' Psalm077A.tex;
sed -i 's/p77.ly/p77B.ly/' Psalm077B.tex;
